# Generated by Django 4.2.3 on 2023-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
