# Generated by Django 4.2.3 on 2023-08-10 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_alter_camera_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='humans_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='humans_dectected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='v_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
