# Generated by Django 4.2.2 on 2023-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_video_humans_checked_video_humans_dectected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
